### ISSUE TITLE
Server plugin refresh triggers before compile completed

### ISSUE THREAD

**Issue by bakapear** [Sarrus1/sourcepawn-vscode#174]
## Basic info

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** Latest (3.0.3)

## Further Information

Having `sourcepawn.refreshServerPlugins` set to `afterCompile` does not wait for the compile to complete and refreshes the plugins instantly.

**Comment by bakapear** [comment]
Probably just needs this to be added after sending terminal text?
https://github.com/microsoft/vscode/blob/1c4b3759ff8c4483e506834e51d7e9fa31ac80b6/src/vs/vscode.d.ts#L5300-L5313

**Comment by Sarrus1** [comment]
I see what's going on here, but your suggestion will only work when the terminal crashes (i think). I will have to test it.

**Comment by Sarrus1** [comment]
> i will have to test it

I did, and the `onDidCloseTerminal` method only fires when you kill the terminal, it's by design apparently, as explained here : https://github.com/microsoft/vscode/issues/97217#issuecomment-625795242

The only option I see is to add a `sleep` function, but that's not very clean...

**Comment by Sarrus1** [comment]
@bakapear please try the latest build [here](https://github.com/Sarrus1/sourcepawn-vscode/releases/tag/v3.0.4). It implements the second fix I proposed above. I still don't know if it works on windows, will have to try later.

**Comment by bakapear** [comment]
On 3.0.4 it prints this in terminal after compile:
```
PS C:\Users\pear\Desktop\plugins> .C:/Users/pear/AppData/Local/sourcemod/scripting/spcomp.exe c:\Users\pear\Desktop\plugins\test.sp -oB:\games\misc\TF2 Server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\plugins\test -iC:/Users/pear/AppData/Local/sourcemod/scripting/include -ic:\Users\pear\Desktop\plugins\include -ic:\Users\pear\Desktop\plugins -O2 -v2
.C:/Users/pear/AppData/Local/sourcemod/scripting/spcomp.exe: The term '.C:/Users/pear/AppData/Local/sourcemod/scripting/spcomp.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
However it does work. The plugin gets compiled and afterwards server plugins refresh.

If the solution isn't ideal though, what about using `window.onDidWriteTerminalData` to listen for the terminal output and proceed when it sees the last line saying `Done.` & abort on `Error. / Errors.`? 
Might be better than a separate process, if it works.

**Comment by Sarrus1** [comment]
> EDIT: Apparently window.onDidWriteTerminalData is not in the API? Can't really test anything here just trying to help ;p

It's only in the proposed API (meaning it won't get implemented) for performance concerns apparently.

I've just pushed another commit that removes the `.`, I think it's not needed here. Please try the latest build again and let me know if it works.

**Comment by bakapear** [comment]
> Please try the latest build again

Have you pushed a new release? I only see 3.0.4 as latest pre-release there.

Manually removing the dot infront still isn't enough as I get this error from the compiler now:
`Server\steamapps\common\Team.sp(0) : fatal error 183: cannot read from file: "Server\steamapps\common\Team.sp"`

Version 3.0.3 put the paths in quotes while 3.0.4 does not anymore:

3.0.3:
```
.'C:\Users\pear\AppData\Local\sourcemod\scripting\spcomp.exe' 'c:\Users\pear\Desktop\plugins\test.sp' -o='B:\games\misc\TF2 Server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\plugins\test' -i='C:\Users\pear\AppData\Local\sourcemod\scripting\include' -i='c:\Users\pear\Desktop\plugins\include' -i='c:\Users\pear\Desktop\plugins' -O2 -v2
```

3.0.4: 
```
.C:\Users\pear\AppData\Local\sourcemod\scripting\spcomp.exe c:\Users\pear\Desktop\plugins\test.sp -oB:\games\misc\TF2 Server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\plugins\test -iC:\Users\pear\AppData\Local\sourcemod\scripting\include -ic:\Users\pear\Desktop\plugins\include -ic:\Users\pear\Desktop\plugins -O2 -v2
```

**Comment by Sarrus1** [comment]
I ended up adding a timeout with a setting to configure the amount of time to wait. It's not clean, but it makes more sense than spawning another process.

**Comment by bakapear** [comment]
Actually another thing comes to mind:

1. Compile plugin with child process exec
2. Redirect stdout/stderr messages to output window
3. Trigger Plugin Refresh

```js
let output = window.createOutputChannel("SourcePawn")
...
output.show()
let child = child_process.exec(compileStr)
child.stdout.on(data => output.appendLine(data.toString())
if(refreshAfterCompile) child.on("close", refreshPlugins)
```

Shouldn't this work in theory? Output window would be better than opening up another terminal in my opinion.

**Comment by Sarrus1** [comment]
The problem with this solution is that outputchannels can't be reaccessed once they were created like [this issue](https://github.com/microsoft/vscode/issues/65108) states. 
If I figure out something I will implement it, as I think it's cleaner.

**Comment by bakapear** [comment]
I experimented a bit with this and I don't think there is a need to access output channels for this to work.
Just create the output channel once before compile and save it to variable to be used for future compiles.

Managed to do it here: https://github.com/bakapear/sourcepawn-vscode/commit/02833934474d72e4e3d322a4f3d9872b7a70f629

**Comment by Sarrus1** [comment]
> Managed to do it here: bakapear@0283393

Looks good!
Can you do a PR so I can merge this?
