### ISSUE TITLE
[BUG] Inconsistent methodmaps error

### ISSUE THREAD

**Issue by zer0k-z** [Sarrus1/sourcepawn-vscode#88]
## Basic info

* **OS:** [Windows]
* **VSCode version:** [v1.59.0]
* **Extension version:** [v2.1.3]

## Further Information

Sometimes go to definition does not work, methodmaps methods are missing or do not show up at all in suggestion.
Test package: [bug.zip](https://github.com/Sarrus1/sourcepawn-vscode/files/6999289/bug.zip)

## To Reproduce

Steps to reproduce the behaviour:
1. Go to `bug.sp`
2. Set `bug.sp` as main file
3. Attempt to go to definition on `DiscordEmbed` or find suggestion after typing `gH_embed.`

## Expected behaviour
Methods and properties are always visible, go to definition leads to the include file

## Error messages

```
 ERR Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
	at Object.t.getSignatureAttributes (c:\Users\zer0.k\.vscode\extensions\sarrus.sourcepawn-vscode-2.1.3\dist\extension.js:2:776253)
	at t.ItemsRepository.provideSignatureHelp (c:\Users\zer0.k\.vscode\extensions\sarrus.sourcepawn-vscode-2.1.3\dist\extension.js:2:758857)
	at q.provideSignatureHelp (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:178805)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:196680
	at We._withAdapter (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:185649)
	at We.$provideSignatureHelp (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:196656)
	at h._doInvokeHandler (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12819)
	at h._invokeHandler (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12503)
	at h._receiveRequest (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:11107)
	at h._receiveOneMessage (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9943)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8039
	at d.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at c.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30060
	at d.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at c.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
	at r._receiveMessage (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:21091)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17969
	at d.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at v.acceptChunk (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:13186)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12534
	at Socket.w (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:13218)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by Sarrus1** [comment]
Can't reproduce with v2.2.0, so I assume this was fixed in a commit in between the two releases.
v2.2.0 will be live in 10 mins.

**Comment by zer0k-z** [comment]
This still happens with local variables. Example attached
[bug.zip](https://github.com/Sarrus1/sourcepawn-vscode/files/7000529/bug.zip)

**Comment by Sarrus1** [comment]
Resolved in v2.2.1
